# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eat. Run. Code.
email: corey@eatrunco.de
description: I like to Eat, Run, and Code. I like to write about all three.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eatrunco.de" # the base hostname & protocol for your site
twitter_username: dchw
github_username:  dchw

# Build settings
markdown: kramdown
